// Terms of service page.

import type { Metadata } from "next";
import Link from "next/link";
import { LegalShell } from "@/components/legal-shell";
import { LegalSection } from "@/components/legal-section";

export const metadata: Metadata = {
  title: "Terms & Conditions — MeetMind",
  description:
    "The terms governing your use of MeetMind, including account responsibilities, acceptable use, and our AI-generated content disclaimer.",
};

const LAST_UPDATED = "September 7, 2026";

const bulletLinkClassName =
  "font-medium text-primary underline-offset-4 hover:underline";

export default function TermsPage() {
  return (
    <LegalShell title="Terms and Conditions" lastUpdated={LAST_UPDATED}>
      <LegalSection id="acceptance-of-these-terms" title="Acceptance of These Terms">
        <p>
          By creating an account or using MeetMind (&ldquo;the
          Service&rdquo;), you agree to these Terms and Conditions. If you do
          not agree, please do not use the Service.
        </p>
        <p>
          You must be at least 13 years old to use the Service, and you must
          provide accurate and complete information when creating an account.
        </p>
      </LegalSection>

      <LegalSection
        id="account-responsibilities"
        title="Account Responsibilities"
      >
        <p>
          You are responsible for keeping your account credentials secure and
          for all activity that occurs under your account. Please do not share
          your password with others, and notify us if you believe your account
          has been compromised.
        </p>
      </LegalSection>

      <LegalSection id="your-content" title="Your Content">
        <p>
          You retain ownership of the recordings you upload to MeetMind and the
          transcripts and summaries generated from them. By uploading content,
          you grant MeetMind a limited license to process, store, and display
          that content solely to provide the functionality of the Service —
          including transcription, summarization, and the chat feature.
        </p>
      </LegalSection>

      <LegalSection
        id="ai-generated-content"
        title="AI-Generated Content"
      >
        <p>
          Transcripts, summaries, and chat responses are generated by artificial
          intelligence and may contain inaccuracies, omissions, or errors. You
          should not rely on AI-generated content as your sole source of
          information for important decisions, and you are responsible for
          reviewing any AI-generated output before relying on it.
        </p>
      </LegalSection>

      <LegalSection id="acceptable-use" title="Acceptable Use">
        <p>You agree not to misuse the Service. Specifically, you must not:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>
            Upload content that you do not have the right to upload or that
            violates the rights of others.
          </li>
          <li>Attempt to access another user&rsquo;s data or account.</li>
          <li>
            Send excessive automated requests or otherwise engage in abuse of
            the Service.
          </li>
          <li>
            Use the Service for any unlawful purpose or in any way that could
            damage or disrupt the Service.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="service-availability" title="Service Availability">
        <p>
          The Service is provided &ldquo;as is&rdquo; and &ldquo;as
          available&rdquo; without warranties of any kind. We do not guarantee
          uninterrupted or error-free operation, and the Service may be
          unavailable from time to time for maintenance or other reasons.
        </p>
      </LegalSection>

      <LegalSection
        id="limitation-of-liability"
        title="Limitation of Liability"
      >
        <p>
          To the maximum extent permitted by law, MeetMind shall not be liable
          for any indirect, incidental, special, or consequential damages
          arising out of or in connection with your use of the Service,
          including loss of data or loss of business.
        </p>
      </LegalSection>

      <LegalSection id="termination" title="Termination">
        <p>
          You may stop using the Service at any time and may delete your account
          and associated data. We may suspend or terminate your account if you
          violate these Terms, including for abuse of the Service or attempts to
          access other users&rsquo; data.
        </p>
      </LegalSection>

      <LegalSection id="changes-to-these-terms" title="Changes to These Terms">
        <p>
          We may update these Terms from time to time. When we do, we will revise
          the &ldquo;Last updated&rdquo; date at the top of this page. Your
          continued use of the Service after changes take effect constitutes
          acceptance of the updated Terms.
        </p>
      </LegalSection>

      <LegalSection id="contact" title="Contact">
        <p>
          If you have questions about these Terms, please reach out through our{" "}
          <Link href="/contact" className={bulletLinkClassName}>
            Contact page
          </Link>
          .
        </p>
      </LegalSection>
    </LegalShell>
  );
}
